services:
  webapp:
    image: "${INGESTION_IMAGE}:${TAG}"
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
      args:
        - USERNAME
        - PASSWORD
    ports:
      - "3000:3000"
    env_file: .env