---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${SURVEY_TAKER_DEPLOYMENT_NAME}
  namespace: ${SURVEY_TAKER_NAMESPACE}
spec:
  maxReplicas: 2 # maximum replicas of pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${SURVEY_TAKER_DEPLOYMENT_NAME} # TARGET name of the deployment the autoscaler need to be run on
  targetCPUUtilizationPercentage: 80 # CPU maximum amount of use on the pod is set to 30%.
