---
apiVersion: v1
kind: Namespace
metadata:
  name: ${SURVEY_TAKER_NAMESPACE}

# Create kubernets service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-sa 
  namespace: ${SURVEY_TAKER_NAMESPACE}

# IAM policy binding between the GSA & KSA service accounts. 
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity
  namespace: ${SURVEY_TAKER_NAMESPACE}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: gke-workload-identity-sa-dev@experiencedotcom-dev.iam.gserviceaccount.com
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:experiencedotcom-dev.svc.id.goog[${SURVEY_TAKER_NAMESPACE}/ksa-sa]

# Annotate the Kubernetes service account with GSA IAM
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: gke-workload-identity-sa-dev@experiencedotcom-dev.iam.gserviceaccount.com
  name: ksa-sa
  namespace: ${SURVEY_TAKER_NAMESPACE}